spring:
  application:
    name: order-logistics-knowledge-service
  config:
    import: optional:nacos:order-logistics-knowledge.yml?group=DEFAULT_GROUP&refreshEnabled=true

server:
  port: ${KNOWLEDGE_SERVER_PORT:8084}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
